name: fishing_paradise
description: "A new Flutter project"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_maps_flutter: ^2.5.3
  weather: ^3.1.1
  geolocator: ^10.1.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  google_sign_in: ^6.1.6
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - .env